# Generated by Django 3.1.5 on 2021-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup_App', '0009_auto_20211016_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
