# Generated by Django 3.1.5 on 2021-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup_App', '0010_auto_20211016_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='a.jpg', null=True, upload_to=''),
        ),
    ]
