# Generated by Django 3.1.5 on 2021-10-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup_App', '0011_auto_20211016_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='summary',
            field=models.TextField(max_length=200),
        ),
    ]
